host = input("\033[32mIngresar host: ")
print("")
print("GET http://" + host + "/[host_port][method]HTTP/1.1[crlf]" + host + "[lf]HEAD http://" + host + "[protocol][crlf]Host: " + host + " [crlf]")
print("")
print("POST http://" + host + " HTTP/1.1[crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]X-Forward-Host: " + host + "[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf][crlf]")
print("")
print("GET http://" + host + "/ HTTP/1.0[crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf][crlf]")
print("")
print("[METHOD] " + host + ":443 HTTP/1.1[crlf]Host: " + host + ":443[crlf]X-Online-Host: " + host + ":443[crlf]X-Forwarded-For: " + host + ":443[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf]Referer: " + host + ":443[crlf][crlf]CONNECT [host_port] [protocol][crlf]Content-Legth: 8799999999999999999999[crlf][crlf]Upgrade: websocket[crlf][crlf]")
print("")
print("CONNECT http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]X-Forward-Host: " + host + "[crlf]Connection: Keep-Alive[crlf]User-Agent: Yes[crlf] CONNECT [host_port] HTTP/1.1[crlf][crlf]")
print("")
print("GET http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf] Access-Control-Allow-Credentials: true, true[lf] Access-Control-Allow-Headers: X-Requested-With,Content-Type, X-Requested-With,Content-Type[lf] Access-Control-Allow-Methods: GET,PUT,OPTIONS,POST,DELETE, GET,PUT,OPTIONS,POST,DELETE[lf] Age: 8, 8[lf] Cache-Control: max-age=86400[lf] public[lf] Connection: keep-alive[lf] Content-Type: text/html; charset=UTF-8[crlf]Content-Length: 9999999999999[crlf]UseDNS: Yes[crlf]Vary: Accept-Encoding[crlf][raw][crlf][crlf][crlf]")
print("")
print("CONNECT [host_port][protocol][crlf]Host: " + host + " [crlf][crlf]CONNECT free.facebook.com;" + host + "internet.org;c.whatsapp.net@[host_port] [protocol][crlf][delay_split]GET http://free.facebook.com;" + host + "internet.org;c.whatsapp.net/ HTTP/1.1[crlf]Host: free.facebook.com;" + host + ")internet.org;c.whatsapp.net[crlf]X-Online-Host: free.facebook.com;" + host + ")internet.org;c.whatsapp.net[crlf]X-Forward-Host: free.facebook.com;" + host + ")internet.org;c.whatsapp.net[crlf]X-Forwarded-For: free.facebook.com;" + host + ")internet.org;c.whatsapp.net[crlf]Connection: Keep-Alive[crlf][crlf]")
print("")
print("GET http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]User-Agent: Yes[crlf]Accept-Encoding: gzip,deflate[crlf]Accept-Charset: ISO-8859-1,utf-8;q=0.7,;q=0.7[crlf]Connection: Basic[crlf]Referer: " + host + "[crlf]Cookie: " + host + " [crlf]Proxy-Connection: Keep-Alive[crlf][crlf][netData][crlf][crlf][crlf]")
print("")
print("GET http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]X-Forward-Host: " + host + "[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf][crlf][delay_split]CONNECT [host_port] [protocol][crlf][crlf]")
print("")
print("GET http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]X-Forward-Host: " + host + "[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf][crlf]")
print("")
print("CONNECT [host_port] [protocol][crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]X-Forward-Host: " + host + "[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf][crlf]")
print("")
print("GET http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]X-Forward-Host: " + host + "[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf][crlf][delay_split]CONNECT [host_port] [protocol][crlf][crlf]")
print("")
print("CONNECT " + host + "@[host_port] [protocol][crlf][delay_split]HEAD http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]X-Forward-Host: " + host + "[crlf]X-Forwarded-For: " + host + "[crlf]Connection: Keep-Alive[crlf][crlf]")
print("")
print("GET http://free.facebook.com;" + host + "internet.org;c.whatsapp.net/ HTTP/1.1[crlf]Host: free.facebook.com;" + host + "internet.org;c.whatsapp.net[crlf]X-Online-Host: free.facebook.com;" + host + "internet.org;c.whatsapp.net[crlf]X-Forward-Host: free.facebook.com;" + host + ")internet.org;c.whatsapp.net[crlf]X-Forwarded-For: free.facebook.com;" + host + ")internet.org;c.whatsapp.net[crlf]Connection: Keep-Alive[crlf][crlf]")
print("")
print("CONNECT [host_port]@" + host + " [protocol][crlf][delay_split]GET http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]X-Forward-Host: " + host + "[crlf]X-Forwarded-For: " + host + "[crlf]Connection: Keep-Alive[crlf][crlf]")
print("")
print("GET http://" + host + "/ HTTP/1.1[crlf][crlf]Host: " + host + "[crlf]Connection: Keep-Alive[crlf]Content-Type: text[crlf]Cache-Control: no-cache[crlf]Connection: close[crlf]Content-Lenght: 20624[crlf][crlf][realData][crlf][crlf]")
print("")
print("[method] " + host + ":443 HTTP/1.1[lf]CONNECT [host_port] [protocol][lf][lf]GET http://" + host + "/ HTTP/1.1Host: " + host + "Connection: closeConnection: closeUser-Agent:[ua][lf]Proxy-Connection: Keep-Alive[lf][host][crlf][lf][delay_split]CONNECT [host_port] [protocol][lf][lf]CONNECT [host_port] [protocol][crlf][realData][crlf][crlf] ")
print("")
print("[immutable][method][host_port][delay_split]GET http://" + host + " HTTP/1.1[netData][crlf]HTTP:mip:80[crlf]X-GreenArrow-MtaID: smtp1-1[crlf]CONNECT http://" + host + "/ HTTP/1.1[crlf]CONNECT http://" + host + "/ HTTP/1.0[crlf][split]CONNECT http://" + host + "/ HTTP/1.1[crlf]CONNECT http://" + host + "/ HTTP/1.1[crlf][crlf]")
print("")
print("[method][host_port]?[split]GET http://" + host + ":80/[crlf][crlf]get [host_port]?[split]OPTIONS http://" + host + "/[crlf]Connection: Keep-Alive[crlf]User-Agent: Mozilla/5.0 (Android; Mobile; rv:35.0) Gecko/35.0 Firefox/35.0[crlf]CONNECT [host_port] [crlf]GET [host_port]?[split]get http://" + host + "/[crlf][crlf][method] mip:80[split]GET " + host + "/[crlf][crlf]: Cache-Control:no-store,no-cache,must-revalidate,post-check=0,pre-check=0[crlf]Connection:close[crlf]CONNECT [host_port]?[split]GET http://" + host + ":/[crlf][crlf]POST [host_port]?[split]GET " + host + ":/[crlf]Content-Length: 999999999[crlf][crlf]")
print("")
print("GET http://" + host + "/ HTTP/1.1[lf]Host: " + host + " User-Agent: Yes Connection: close Proxy-Connection: Keep-Alive [crlf][crlf]CONNECT [host_port][protocol][crlf][crlf][immutable] ")
print("")
print("GET http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf] Access-Control-Allow-Credentials: true, true[lf] Access-Control-Allow-Headers: X-Requested-With,Content-Type, X-Requested-With,Content-Type[lf] Access-Control-Allow-Methods: GET,PUT,OPTIONS,POST,DELETE, GET,PUT,OPTIONS,POST,DELETE[lf] Age: 8, 8[lf] Cache-Control: max-age=86400[lf] public[lf] Connection: keep-alive[lf] Content-Type: text/html; charset=UTF-8[crlf]Content-Length: 9999999999999[crlf]UseDNS: Yes[crlf]Vary: Accept-Encoding[crlf][raw][crlf][crlf][crlf]")
print("")
print("GET http://" + host + "/ HTTP/1.1 Host: " + host + "/ User-Agent: Yes Connection: close Proxy-Connection: update [crlf][crlf][netData][crlf][crlf][crlf]")
print("")
print("GET http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]Content-Type: text/html; charset=iso-8859-1[crlf]Connection: close[crlf][crlf][crlf]User-Agent: [ua][crlf][crlf]Referer: " + host + "[crlf]Cookie: " + host + "[crlf]Proxy-Connection: Keep-Alive [crlf][crlf]CONNECT [host_port] [protocol][crlf][crlf][crlf]")
print("")
print("GET http://" + host + "/ HTTP/1.1 Host: " + host + " Upgrade-Insecure-Requests: 1 User-Agent: Mozilla/5.0 (Linux; Android 5.1; LG-X220 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 Referer: http://" + host + " Accept-Encoding: gzip, deflate, sdch Accept-Language: pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4 Cookie: _ga=GA1.2.2045323091.1494102805; _gid=GA1.2.1482137697.1494102805; tfp=80bcf53934df3482b37b54c954bd53ab; tpctmp=1494102806975; pnahc=0; _parsely_visitor={%22id%22:%22719d5f49-e168-4c56-b7c7-afdce6daef18%22%2C%22session_count%22:1%2C%22last_session_ts%22:1494102810109}; sc_is_visitor_unique=rx10046506.1494105143.4F070B22E5E94FC564C94CB6DE2D8F78.1.1.1.1.1.1.1.1.1 Connection: close Proxy-Connection: Keep-Alive [crlf][netData][crlf][crlf][crlf]")
print("")
print("GET http://" + host + "[crlf] HTTP/1.1[crlf]Host: " + host + "[crlf]User-Agent: [ua][crlf]Connection: close [crlf] Referer:http://" + host + "[crlf] Content-Type: text/html; charset=iso-8859-1[crlf]Content-Length:0[crlf]Accept: text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5[crlf][raw][crlf][crlf]")
print("")
print("GET https://" + host + "/ HTTP/1.1 Host: " + host + "[crlf]User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.13) Gecko/20101203 Firefox/3.6.13 Accept-Language: en-us,en;q=0.5 Accept-Encoding: gzip,deflate Accept-Charset: ISO-8859-1,utf-8;q=0.7,;q=0.7 Keep-Alive: 115 Connection: keep-alive Referer: " + host + " Cookie: " + host + " Proxy-Connection: Keep-Alive [crlf][crlf][netData][crlf] [crlf][crlf]")
print("")
print("GET [host_port]@" + host + " HTTP/1.1[crlf]X-Real-IP:mip[crlf]X-Forwarded-For:http://" + host + "/ http://" + host + "/[crlf]X-Forwarded-Port:" + host + "[crlf]X-Forwarded-Proto:http[crlf]Connection:Keep-Alive[crlf][crlf][instant_split]CONNECT [ssh]HTTP/1.0[crlf][crlf]")
print("")
print("CONNECT http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]Proxy-Connection: keep-alive[crlf]Connection: keep-alive[crlf][crlf][method] [host_port] [protocol][crlf]Proxy-Authorization: [auth][crlf]Proxy-Connection: keep-alive[crlf]Connection: keep-alive[crlf][crlf]")
print("")
print("[method] [host_port] [protocol][crlf]Proxy-Connection: keep-alive[crlf]Connection: keep-alive[crlf][crlf][split_delay]MOVE http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]Proxy-Connection: keep-alive[crlf]Connection: keep-alive[crlf][crlf]")
print("")
print("[method] [host_port] [protocol][crlf]Proxy-Authorization: [auth][crlf]Proxy-Connection: keep-alive[crlf]Connection: keep-alive[crlf][crlf]")
print("")
print("MOVE http://" + host + "/ HTTP/1.0[crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]Proxy-Connection: keep-alive[crlf]Connection: keep-alive[crlf][crlf][method] [host_port] [protocol][crlf]Proxy-Authorization: [auth][crlf]Proxy-Connection: keep-alive[crlf]Connection: keep-alive[crlf][crlf]")
print("")
print("GET /datos-por-demanda/ HTTP/1.1 9999999999 Connection: Keep-Alive[auth] Host: " + host + ":80 Connection: Keep-Alive[auth]Content-Length: 999999999 Host: " + host + ":80[crlf][crlf]Accept-Encoding: gzip[crlf][crlf]Content-Length: 999999999[crlf][crlf]")
print("")
print("GET http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]User-Agent: [ua][lf][host]@" + host + " [protocol][lf][lf]")
print("")
print("CONNECT [host_port]HTTP/1.0[host][lf][cr]GET " + host + " HTTP/1.1 Connection: Close keep-alive Content-Length: 9999999999 [crlf][crlf][netData][crlf] [host_port]GET http://" + host + " HTTP/1.0[lf]")
print("")
print("GET http://" + host + "[crlf] HTTP/1.1[crlf]Host: " + host + "[crlf]User-Agent: [ua][crlf]Connection: close [crlf] kkReferer:http://" + host + "[crlf] Content-Type: text/html; charset=iso-8859-1[crlf]Content-Length:0[crlf]Accept: text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5[crlf][raw][crlf] [crlf]")
print("")
print("CONNECT [host_port][protocol][crlf][delay_split]GET http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]Connection: Keep-Alive[crlf]x-amz-id-2: +bnliBcDYxWL++PEO8kRY18ng+fHsuiIINYg/e8YrGUJLYLK3RJ6ko7OUiYCMNIiWMzHPmTYUrE=[crlf]User-Agent: [ua][crlf][crlf][split][raw]")
print("")
print("CONNECT [host_port]@" + host + " [protocol][crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]X-Forward-Host: " + host + "[crlf]X-Forwarded-For: " + host + "[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf]CONNECT [host_port] [protocol][crlf][crlf]")
print("")
print("GET / HTTP/1.1[crlf]Host: " + host + "[crlf]User-Agent: [ua][crlf]Accept: Yes[crlf]Connection: keep-alive[crlf]Upgrade: websocket[crlf][crlf]")
print("")
print("GET / HTTP/1.3Host: " + host + " [host_port][crlf][crlf][split]REAL / HTTP/1.1[crlf][crlf]Host: " + host + "Upgrade: Websocket[crlf][crlf]")
print("")
print("GET / HTTP/1.1[crlf]Host: " + host + "[crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]")
print("")
print("ACL 127.0.0.1:8989;vegetay HTTP/1.1[crlf]Host: [rotate=www.Pandora.com;www.google.net;www.deezer.com;www.pokemon.com;vegetay.waze.com;books.google.com;;" + host + "/~textrend/index.pl/jv/10/http/][lf]")
print("")
print("POST wss://" + host + " HTTP/1.1[crlf]Host: " + host + "[crlf]User-Agent: " + host + "[crlf] Connection: Keep-Alive[crlf]Upgrade: websocket[crlf][crlf]")
print("")
print("GET wss\\\\\\/" + host + "\\\\\\/DNS\\\\\\/1.1\\\\\\/crfl\\\\\\/Host: t.me\\\\\\/" + host + "[crlf] charset=UTF-8[crlf]Content-Length: 999999999999999[crlf]UseDNS: Yes[crlf]Vary: Accept-Encoding[crlf][raw][crlf][crlf][crlf][crlf][crlf]")
print("")
print("HEAD / HTTP/1.1[crlf]Host:" + host + "[lf]Host:" + host + "[lf]Upgrade: Websocket[crlf]Connection: Upgrade[crlf][crlf]")
print("")
print("HEAD / HTTP/1.1[crlf]Host: " + host + "[crlf] redireccion:" + host + "[crlf]Connection: Upgrade[crlf]User-Agent: [ua]" + host + " [crlf]Upgrade: websocket[crlf]Expect: 100-continue[crlf][crlf]")
print("")
print("HEAD wss://" + host + " HTTP/1.4[lf]Host:" + host + "[lf][crlf][crlf][lf][instant_split][lf][lf]UNLOCK / HTTP/1.1[lf]User-Agent: Mozilla/5.0 (X11; U; Linux x86_64; en-gb) AppleWebKit/534.35 (KHTML like Gecko) Chrome/35.0.1916.141 Safari/537.36 Host: " + host + "[lf]Connection: keep-alive Proxy-Connection: keep-alive [crlf][crlf]Upgrade: websocket[crlf][crlf]")
print("")
print("DELETE /" + host + " HTTP/1.9[crlf]Host: " + host + "[crlf][crlf][split]GET- / HTTP/1.1[crlf]Host: [host_port][crlf]Upgrade: Websocket [crlf][crlf]")
print("")
print("GET / HTTP/1.1[crlf]Host: " + host + "[crlf]Expect: 100-continue[lf][lf][split][lf][lf]ACL /Real/ HTTP/1.1[lf]Host: " + host + "[lf]Expect: 100-continue[lf]Connection: Upgrade[lf]Upgrade: websocket[lf]User-Agent: Googlebot/2.1 (+http://www.google.com/bot.html)[lf][lf]")
print("")
print("GET https://" + host + " HTTP/1.1[crlf]Host: " + host + "[crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf]CONNECT [host_port] [protocol][crlf][crlf]")
print("")
print("GET wess://" + host + " HTTP/1.1[crlf]Host: " + host + "[crlf]Upgrade: websocket[crlf]Connection: Upgrade[crlf][crlf]")
print("")
print("GET wess://" + host + " HTTP/1.1[crlf]Host: " + host + "[crlf]Upgrade: websocket[crlf]Connection: Upgrade[crlf][crlf]GET ws://" + host + "/ HTTP/1.1[crlf]Host: [host][crlf][upws][crlf][crlf] GET ws://" + host + "/ HTTP/1.1[crlf]Host: [host][crlf][upws][crlf][crlf]")
print("")
print("GET / HTTP/1.1[crlf]Host: " + host + "[crlf]User-Agent: [ua][crlf]Accept: Yes[crlf]Connection: keep-alive[crlf]Upgrade: websocket[crlf][crlf]")
print("")
print("POST http://" + host + ":8080/CaptivePortal/?reared=005/SESSIONID=huawei130.huawei.claro;3648315128;520;14564&SITEID=2&RG=12&INST=1211&LOC=7160100300425105 Host:" + host + " User-Agent: Dalvik/2.1.0 (Linux; U; Android 9; LM-X420 Build/PKQ1.190302.001) CONNECT ip:puerto HTTP/1.0 [crlf][crlf]")
print("")
print("GET http://" + host + "/recargas/ HTTP/1.1[crlf]User-Agent: http://mobile.twitter.com" + host + "/recargas/[ua][crlf]Connection: Keep-Alive[crlf]Referer: " + host + "/recargas/[crlf][crlf]CONNECT [host_port] [protocol][crlf][crlf]POST http://" + host + "/recargas/ HTTP/1.1[crlf]User-Agent: Yes\rConnection: close\rProxy-Connection: Keep-Alive [crlf][netData][crlf][crlf]")
print("")
print("POST http://" + host + "/ [protocol][crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]Connection: Keep-Alive[crlf][crlf]")
print("")
print("CONNECT ip:puerto GET http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]X-Forward-Host: " + host + "[crlf]X-Forwarded-For: host.com[crlf]User-Agent: [ua][crlf][crlf]")
print("")
print("GET / HTTP/1.1[crlf]Host: " + host + "[crlf]User-Agent: [ua][crlf]Accept: Yes[crlf]Connection: keep-alive[crlf]Upgrade: websocket[crlf][crlf]")
print("")
print("CONNECT [host_port]@" + host + ":443 [protocol][crlf]Host: " + host + ":443[crlf]X-Online-Host: " + host + ":443[crlf]X-Forward-Host: " + host + ":443[crlf]X-Forwarded-For: " + host + ":443[crlf]Connection: Keep-Alive[crlf]User-Agent: Mozilla/5.0 (Linux; Android 5.1.1; Nexus 7 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.78 Safari/537.36 OPR/30.0.1856.93524[crlf]Referer: " + host + ":443[crlf][crlf]")
print("")
print("GET wss://bug.com/ [protocol][crlf]Host:" + host + "[crlf]Connection: Keep-Alive[crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]")
print("")
print("BMOVE /" + host + " HTTP/1.1[lf]Host:" + host + "[lf][lf]BDELETE h2://" + host + "HTTP/1.1[lf]Host: " + host + " [lf]Upgrade: websocket[crlf][crlf]")
print("")
print("CONNECT " + host + "@[host_port] [protocol][crlf][delay_split]GET http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf][crlf]")
print("")
print("CONNECT 127.0.0.1:8799[split][crlf] HTTP/1.3 [crlf]Host: " + host + "www.au.download.windowsupdate.com;www.icloud.com;p16.muscdn.com;mcompany.netmarble.com;www.pubgmobile.com;www.itau.com.br;ems25.your-freedom.de;www.godaddy.co;amazon.com;espn.com;a.applovin.com;bing.com;spotify.com;ivivo.terra.com;apple.com;netflix.com;m.youtube.com.br;deezer.com;cdn4.com.line.naver.jp.fbme;d1n212ccp6ldpw.cloudfront.net;sun.iflix.com;global.ssl.fastly.net;prx2tst.global.ssl.fastly.net;prod.global.ssl.fastly.net;www.cloudflare.com.br;bb.com.br;santander.com.br;www.espn.com;www.microsoft.com;e.crashlytics.com;www.sky.com.br;adash.man.aliyuncs.com;imgur.com;www.reddit.com;www.hooq.tvp;www.crashlytics.com;www.bing.com;www.cabify.com[crlf][crlf]")
print("")
print("CONNECT 127.0.0.1:8799[split][lf] HTTP/1.0 [lf]Host: [rotate=" + host + "xvideos.com;m.youtube.com;www.tripadvisor.com][crlf][crlf]")
print("")
print("[split][protocol]SSH/CONNECT [crlf]HTTP/302 [lf]Host: [rotate=" + host + "www.mi.com/global;www.qq.com;joox.com;pinterest.com;netshoes.com;www.google.com;connect.facebook.net][crlf][crlf]")
print("")
print("CONNECT [host_port] [split]GET " + host + " EHTTP/1.1 400 OK[lf]HTTPHost:" + host + "[lf]HTTPConnection: Keep-Alive[lf][lf][raw][lf][instant_split]User-Agent: [ua][lf][lf]Content-Length: 999999999[lf][lf] GET HTTP/1.1 200 OK[crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]X-Forward-Host: " + host + "[crlf]Proxy-Connection: Close[crlf][crlf]User-Agent: [ua][crlf][crlf]Content-Length: 999999999999999[crlf][crlf]")
print("")
print("CONNECT https://" + host + "/ [protocol][crlf]POST [host_port] HTTP/1.1[crlf]Host: " + host + "[crlf]Referer: " + host + "[crlf]Content-Length: 999999999[crlf]X-Online-Host: " + host + "[crlf]Proxy-Connection: keep-alive[crlf]Connection: keep-alive[crlf]User-Agent: [ua][crlf][crlf][split][method] [host_port] [protocol][crlf]Proxy-Authorization: [auth][crlf]Proxy-Connection: keep-alive[crlf]Connection: keep-alive[crlf][crlf]")
print("")
print("CONNECT [host_port] HTTP/1.1[crlf][crlf][delay_split]PUT https://" + host + "/ [protocol][crlf]Host: " + host + "[crlf]X-Online-Host: " + host + "[crlf]X-Forward-Host: " + host + "[crlf]Connection: Keep-Alive[crlf][crlf]")
print("")
print("GET http://" + host + "/ HTTP/1.1[crlf]Host: " + host + "[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf][crlf][delay_split]CONNECT [host_port] [protocol][crlf][crlf]")
print("")
print("[split][method][host_port]GET http://" + host + " [protocol][crlf]Proxy-Authorization: [auth]Host: " + host + "[crlf][crlf]")
print("")
print("[split] [method] [host_port]GET http://" + host + "[protocol][crlf]Proxy-Authorization: [auth]Host: " + host + "[crlf][crlf]")
print("")
print("CONNECT [host_port]@RealStrategy[protocol][crlf]Host: " + host + "[crlf]X-Forwarded-For: " + host + "[crlf]Connection: Keep-Alive[crlf]User-Agent:999999999 [ua][crlf][crlf]")
print("")
print("GET [host_port]@[rotate=www.whatsapp.com;m.facebook.com;www.instagram.com;www.spotify.com] HTTP/1.1[crlf][crlf]GET http://[rotate=www.whatsapp.com;m.facebook.com;www.instagram.com;www.spotify.com]/ [protocol][crlf]Host: [rotate=www.whatsapp.com;m.facebook.com;www.instagram.com;www.spotify.com][crlf]X-Online-Host: [rotate=www.whatsapp.com;m.facebook.com;www.instagram.com;www.spotify.com][crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf][crlf]")
print("")
